version: '3.8'
services:
  devcontainer_1:
    build: 
      context: .devcontainer/container_1
      dockerfile: Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - type: bind
        source: . 
        target: /workspace # .. means one level up from .devcontainer/
    working_dir: /workspace
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video2:/dev/video2"
      - "/dev/video4:/dev/video4" 
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY:-/tmp/.docker.xauth}
    user: root
    command: bash
    tty: true
    stdin_open: true

    
  #devcontainer_2:
  #  build: 
  #    context: .devcontainer/container_2
  #    dockerfile: Dockerfile
    #command: sleepinfinty
  #harmonic:
  #  image: althack/gz:harmonic-base
  #  environment:
  #    - DISPLAY=${DISPLAY}
  #    - XAUTHORITY=${XAUTHORITY:-/tmp/.docker.xauth}
  #    - LIBGL_ALWAYS_SOFTWARE=1  # Force software rendering
  #    - MESA_GL_VERSION_OVERRIDE=3.3
  #  volumes:
  #    - /tmp/.X11-unix:/tmp/.X11-unix:rw
  #  user: root
  #  network_mode: host  # Use host networking
  #  stdin_open: true
  #  tty: true
  #  command: gz sim
